### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by apawsey** [Zevran/materialize-loader#2]
I noticed you removed the dependencies in a recent commit.  Just wondering why because after installing your package, I had to manually install node-sass to get it to work.

Just a note.

**Comment by Zevran** [comment]
Hi,

Thanks for reporting this :)
Maybe it should be specified as peer dependency ? What do you think ?

Regards,

**Comment by Zevran** [comment]
Resolved.
Add node-sass to dependencies - acdabd2f684e43c5befd096527d2cf3d5e00cba2
