### ISSUE TITLE
Example webpack.config.js

### ISSUE THREAD

**Issue by methodbox** [Zevran/materialize-loader#21]
I have yet to be able to get this or any other configuration to properly load Materialize (or for that matter, jQuery, which is spotty at best) with Webpack.

My feeling so far is that webpack is a pile of shit.

It would be useful if you could please post an example webpack.config.js that actually works.

Your documentation is unclear as to exactly where the example code goes, and continually throws errors.

**Comment by Zevran** [comment]
materialize-loader is not supposed to give support on webpack configurations.
I recommend you to look a create-react-app from @facebookincubator or react-boilerplate from @mxstbr

**Comment by methodbox** [comment]
I understand webpack. But if your example as to how to enable this loader is unclear, why would you not think that you should provide some guidance for that?

It doesn't matter, anyway since your loader doesn't actually work correctly. It still improperly loads jQuery, which is due to the nature of JQuery, not your loader.

**Comment by Zevran** [comment]
If you know webpack you know how to use this package. The documentation shows exactly where to put piece of code.

And the package does not need to load jQuery because materialize-css itself doesn't load jQuery. It is required as an external dependency, not internal.

**Comment by methodbox** [comment]
JQuery 2.1.4 is included in the NPM module for materialize-css.
