### ISSUE TITLE
Uncaught TypeError: k.velocity is not a function

### ISSUE THREAD

**Issue by Raevox** [Zevran/materialize-loader#25]
Good day! I've been trying to setup Materialize with Webpack but I can't seem to get everything working quite right.

Here's my `webpack.config.js`:
```js
const path = require('path');

const webpackConfig = {
  entry: [
    'babel-polyfill',
    'materialize-loader',
    path.join(__dirname, './src/app.js')
  ],
  output: {
    path: path.join(__dirname, './public/scripts'),
    filename: 'app.bundle.js',
    publicPath: '/scripts/'
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        include: path.join(__dirname, './src'),
        loader: 'babel',
        query: {
          presets: [ 'es2015' ]
        }
      },
      {
        test: /\.(scss|sass)$/,
        include: path.join(__dirname, './src'),
        loader: 'style!css!resolve-url!sass?sourceMap!sass-resources'
      },
      {
        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url?limit=10000&mimetype=application/font-woff'
      },
      {
        test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'file'
      },
      {
        test: /\.(png|jpg|jpeg)$/,
        loader: 'file'
      }
    ]
  },
  devTool: 'eval',
  devServer: {
    contentBase: path.join(__dirname, './public'),
    inline: true
  },
  sassLoader: {
    includePaths: [
      path.join(__dirname, './node_modules/bourbon/app/assets/stylesheets')
    ]
  },
  sassResources: [
    path.join(__dirname, './node_modules/normalize-css/normalize.css'),
    path.join(__dirname, './node_modules/bourbon/app/assets/stylesheets/_bourbon.scss')
  ],
};

module.exports = webpackConfig;
```

...and my `app.js`:
```js
/**
 * Import non-Angular frameworks and libraries
 */
import uuid from 'uuid';
import $ from 'jquery';
import 'materialize-css';

/**
 * Import Angular and wanted dependencies
 */
import angular from 'angular';
import 'angular-sanitize';

/**
 * Initialize Angular app module
 */
import './module.js';

/**
 * Define re-usable filters and services
 */
import './filter/trust.js';
import './filter/titlecase.js';
import './service/inventory.js';

/**
 * Define application controllers
 */
import './controller/inventory.js';

/**
 * Import user stylesheets
 */
import './app.scss';

(() => {
  window.jQuery = $;
  $('.modal').modal();
})();
```

Upon clicking a modal, I get `app.bundle.js:59678 Uncaught TypeError: k.velocity is not a function` and I can't quite figure out why.

I tried installing `velocity-animate` and `import`ing it but that produced the same result. Any help would be appreciated. Thanks!

**Comment by Zevran** [comment]
Hi,

You have to know that materialize-loader only loads styles files into the webpack bundle. It does not require to load materialize javascript library and it is not his role.

This error comes from the import of materialize-css himself, an umd library which is not supported by babel-loader.

You can exclude it from babel parsing with the exclude property in the loader.

I hope it helped you :)

**Comment by Raevox** [comment]
Ah, wow. Thanks! I figured it was something like that.

I tried excluding `path.join(__dirname, './node_modules/materialize-css/bin/materialize.js')` from by babel loader but the error persists.

There is a [workaround I found that works](https://github.com/InfomediaLtd/angular2-materialize/issues/20#issuecomment-236180979), but I'm still interested in a solution that doesn't involve loading dependencies straight into the markup.

Sorry to bother you about a problem that's not exactly yours, and thanks for the help regardless of the fact!

**Comment by Zevran** [comment]
Webpack behavior is to load / parse types of ressources with appropriated loaders, if you don't specify precisely how to load materialize library, it will be loaded / parsed as the others ressources so the workaround you linked might be the only solution to your problem.

Maybe you can check these links :
 - https://github.com/Dogfalo/materialize/issues/1229
 - https://github.com/erikras/react-redux-universal-hot-example/issues/596
