### ISSUE TITLE
Does it import JS code as well?

### ISSUE THREAD

**Issue by shanika** [Zevran/materialize-loader#27]
Hi I'm trying to configure my project using materialize.config.js file. Does it suppose to include materialize-css javascript code as well? Or should we import JS code separately?  Cheers

**Comment by Zevran** [comment]
Hi,

Thanks for using materialize-loader !
No it actually only loads sass content into your webpack bundle. You have to import JS code separately.

Tell me if it's ok for you so I can close the issue.

Regards

**Comment by shanika** [comment]
Hi Zevran, Thank you for the answer. Yes I managed to import javascript code separatly. Cheers.
