### ISSUE TITLE
No loading of materialize Javascript

### ISSUE THREAD

**Issue by apawsey** [Zevran/materialize-loader#3]
Hi,

The loader does bring in the materialize styles, but I don't see it bringing in the javascript dependency anywhere?  Have I missed something, or is this not yet included?

**Comment by Zevran** [comment]
Hi,

To include materialize javascript bundle you need to require it in your main app file (e.g. App.js)

#### Common syntax
```
require('materialize-css');
```

#### ES6 Syntax
```
import 'materialize-css';
```

Regards

**Comment by prolink007** [comment]
After adding `import 'materialize-css';`, i am still getting the following error:

`TypeError: jQuery(...).collapsible is not a function`
