### ISSUE TITLE
New release with the support of webpack 2 ?

### ISSUE THREAD

**Issue by Farkal** [Zevran/materialize-loader#30]
I am using webpack 2.4.1 and when i do `require("materialize-loader");` i got:

> ERROR in ../~/materialize-loader/index.js
> Module not found: Error: Can't resolve './materialize-styles'

I look to the branch network and i saw that you fix something with webpack2 in develop but this haven't been released yet.

**Comment by alexduch** [comment]
+1

I am currently using the content of the `develop` branch by declaring the dependency like this:
```json
"materialize-loader": "github:zevran/materialize-loader#develop",
```

But it would be nice to have those changes released.

**Comment by Zevran** [comment]
I am sorry for the delay of response, I am currently working on it !

**Comment by Zevran** [comment]
@Farkal @alexduch It should be solved :)

**Comment by alexduch** [comment]
Thank you very much !
I tested this morning and it works as expected.
