### ISSUE TITLE
Webpack dumps font files in root dir

### ISSUE THREAD

**Issue by leccles1** [Zevran/materialize-loader#32]
So I've recently began using the materialize-loader after struggling to find a way to easily add materializecss into my web apps.

One thing I've noticed is that after running webpack it dumps the font files (.woff, .woff2) in the root directory. I thought maybe if I put my materialize.config.js & materialize.config.scss into a directory (materialize-config/) and edit my webpack entry to be

   ```
entry: [
    'script!jquery/dist/jquery.min.js',
    'materialize-loader!./materialize-config/materialize.config.js',
    './app/app.jsx'
  ], 
```

it would dump the font files into there, however this was not the case.

Is there currently a config option to define a folder to put the fonts into?

**Comment by Zevran** [comment]
Hi,

The fonts are managed by the **file-loader** and the **url-loader**, you can configure output folder with the output object in your webpack configuration -> [https://webpack.js.org/configuration/output](https://webpack.js.org/configuration/output).

**Comment by leccles1** [comment]
Great, thanks for the link will take a look into it :)
