### ISSUE TITLE
Why have no description url-loader and file-loader?

### ISSUE THREAD

**Issue by devjin0617** [Zevran/materialize-loader#8]
First npm install to url-loader, file-loader..

but have no readme file

**Comment by Zevran** [comment]
Could you explain a little bit more ?

**Comment by devjin0617** [comment]
um.. im npm install to your `materialize-loader` library.

but i not append to url-loader and file-loader of dependencies in my project. next to create the webpack config and command to `npm start`. after print to error message `not found module "url" and "file`. because i not see the loader install description

p.s sorry. i don't speak english : (

**Comment by Zevran** [comment]
No problem,

materialize-loader doesn't use at all any of these packages but if you want to properly load fonts and images from materialize-css you have to include file-loader and url-loader according to the webpack config example in the readme.

I simply suggest you install these dependencies manually and I will add a warning in the readme to prevent this type of mistake.

**Comment by devjin0617** [comment]
thankyou! this is good project!
